name: Run Python Unittests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-n-run-tests:
    name: Build the project and run unittests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python 3.11
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      
      - name: Install dependencies
        run: poetry install --without dev --no-interaction

      - name: Run Tests
        run: |
          source .venv/bin/activate
          python3 -m unittest tests.test_plug_controller --verbose
